# https://github.com/OAI/OpenAPI-Specification/blob/master/examples/v2.0/yaml/petstore.yaml
swagger: "2.0"
info:
  version: 1.0.0
  title: Half a beast
basePath: /v1
paths:
  /get-voters-where:
    get:
      summary: get voters where
      operationId: api.get_voters_where
      tags:
        - data
      parameters:
        - name: county
          in: query
          description: county
          required: false
          type: integer
        - name: month
          in: query
          description: month
          required: false
          type: integer
        - name: affiliation
          in: query
          description: affiliation
          required: false
          type: integer
        - name: status
          in: query
          description: status
          required: false
          type: integer
        - name: limit
          in: query
          description: limit
          required: false
          type: integer          
      responses:
        default:
          description: data
          schema: 
            type: object